package:
  name: yoga-docker-compose
  publish:
    version: 0.1.0
    license: MIT
    location:
      githubOwner: rowtype-yoga
      githubRepo: purescript-yoga-backend-stack
      subdir: packages/yoga-docker-compose
  dependencies:
    - aff: ">=7.0.0 <8.0.0"
    - effect: ">=4.0.0 <5.0.0"
    - node-child-process: ">=9.0.0 <12.0.0"
    - prelude: ">=6.0.0 <7.0.0"
    - node-child-process: ">=9.0.0 <10.0.0"
